<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net8.0-macos</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Avalonia.Skia.Lottie" Version="11.0.0" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
        <PackageReference Include="FFmpeg.AutoGen" Version="7.1.1" />
        <PackageReference Include="FFmpeg.AutoGen.Abstractions" Version="7.1.1" />
        <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.4-pre348" />
        <PackageReference Include="ManagedBass" Version="3.1.1" />
        <PackageReference Include="ManagedBass.Wasapi" Version="3.1.1" />
        <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
        <PackageReference Include="OpenRGB.NET" Version="3.1.1" />
        <PackageReference Include="Polly" Version="8.4.0" />
        <PackageReference Include="Serilog" Version="4.0.1" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
        <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
        <PackageReference Include="SixLabors.ImageSharp" Version="2.1.3" />
        <PackageReference Include="SkiaSharp" Version="2.88.9" />
        <PackageReference Include="System.IO.Ports" Version="9.0.0-preview.5.24306.7" />
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="obj\**" />
        <Compile Remove="Models\Geography\Group.cs" />
        <Compile Remove="Models\Lighting\Zone\LightingZoneGroup.cs" />
        <Compile Remove="Models\Lighting\Zone\LightingZoneGroupContainerFigure.cs" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Remove="obj\**" />
    </ItemGroup>

    <ItemGroup>
        <None Remove="obj\**" />
    </ItemGroup>

    <!-- Include only ScreenCapture.NET.SCK and ScreenCapture.NET.AV for macOS -->
    <ItemGroup Condition="'$(TargetFramework)' == 'net8.0-macos'">
        <ProjectReference Include="../ScreenCapture.NET.SCK/ScreenCapture.NET.SCK.csproj" />
        <ProjectReference Include="../ScreenCapture.NET.AV/ScreenCapture.NET.AV.csproj" />
    </ItemGroup>
    <!-- Include only ScreenCapture.NET.SCK and ScreenCapture.NET.AV for Linux -->
    <ItemGroup Condition="'$(TargetFramework)' == 'net8.0' AND '$(RuntimeIdentifier)' == 'linux-x64'">
        <ProjectReference Include="../ScreenCapture.NET.X11/ScreenCapture.NET.X11.csproj" />
    </ItemGroup>
    <!-- Include all other project references for non-macOS builds -->
    <ItemGroup>
        <ProjectReference Include="../Avalonia.Gif/Avalonia.Gif.csproj" />
        <ProjectReference Include="../ScreenCapture.NET.DX11/ScreenCapture.NET.DX11.csproj" />
        <ProjectReference Include="../ScreenCapture.NET.DX9/ScreenCapture.NET.DX9.csproj" />
        <ProjectReference Include="../ScreenCapture.NET/ScreenCapture.NET.csproj" />
        <ProjectReference Include="..\AmbinityServer\AmbinityServer.csproj" />
        <ProjectReference Include="..\Draw2D.Core\Draw2D.Core.csproj" />
        <ProjectReference Include="..\OpenRGB.NET\OpenRGB.NET.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Notification\" />
    </ItemGroup>
</Project>
