<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0-macos15.0</TargetFramework>
        <SupportedOSPlatformVersion>12.3.0</SupportedOSPlatformVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <AssemblyVersion>6.0.9.1</AssemblyVersion>
        <FileVersion>6.0.9.1</FileVersion>
        <InformationalVersion>6.0.9.1</InformationalVersion>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Models\" />
        <AvaloniaResource Include="Assets\**" />
        <Folder Include="SystemUtilities/" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.2.7" />
        <PackageReference Include="Avalonia.Desktop" Version="11.2.7" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.7" />
        <!--Condition
        below is needed to remove Avalonia.Diagnostics package from build output in Release
        configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.2.7">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
        <PackageReference Include="FluentAvaloniaUI" Version="2.2.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../Ambinity/Ambinity.csproj" />
    </ItemGroup>
</Project>
