<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TargetFramework>netstandard2.1</TargetFramework>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <LangVersion>12</LangVersion>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
        <PackageReference Include="Serilog" Version="4.0.1" />
    </ItemGroup>
       <ItemGroup>
        <EmbeddedResource Include="Infrastructure\Resources\EmbeddedResources\Locales\**" />
        <EmbeddedResource Include="Infrastructure\Resources\EmbeddedResources\AmbinityDevices\**" />
        <EmbeddedResource Include="Infrastructure\Resources\EmbeddedResources\Images\**" />
        <EmbeddedResource Include="Infrastructure\Resources\EmbeddedResources\AmbinityLightingProfiles\**" />
    </ItemGroup>
</Project>
