<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>12</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Avalonia" Version="11.1.3" />
      <PackageReference Include="QuickGraph" Version="3.6.61119.7" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Shapes\Custom\" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="obj\Debug\netstandard2.1\Draw2D.Core.AssemblyInfoInputs.cache" />
      <Content Include="obj\Debug\netstandard2.1\Draw2D.Core.assets.cache" />
      <Content Include="obj\Debug\netstandard2.1\Draw2D.Core.csproj.AssemblyReference.cache" />
      <Content Include="obj\Debug\netstandard2.1\Draw2D.Core.csproj.CoreCompileInputs.cache" />
      <Content Include="obj\Debug\netstandard2.1\Draw2D.Core.csproj.FileListAbsolute.txt" />
      <Content Include="obj\Debug\netstandard2.1\Draw2D.Core.dll" />
      <Content Include="obj\Debug\netstandard2.1\Draw2D.Core.pdb" />
      <Content Include="obj\Debug\netstandard2.1\Draw2D.Core.sourcelink.json" />
    </ItemGroup>

    <ItemGroup>
      <Compile Include="obj\Debug\netstandard2.1\.NETStandard,Version=v2.1.AssemblyAttributes.cs" />
      <Compile Remove="obj\**" />
    </ItemGroup>

    <ItemGroup>
      <AvaloniaXaml Remove="obj\**" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="obj\**" />
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Remove="obj\**" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="obj\**" />
    </ItemGroup>

</Project>
